//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubsProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_CountryOrdersInfo
    {
        public int Id { get; set; }
        public string ShipCountry { get; set; }
        public Nullable<int> CountryOrders { get; set; }
        public Nullable<decimal> CountryTotal { get; set; }
        public Nullable<double> CountryTotalDiscount { get; set; }
        public Nullable<decimal> CountryAvg { get; set; }
        public Nullable<double> CountryAvgDiscount { get; set; }
        public Nullable<decimal> FreightAvg { get; set; }
    }
}
